### ISSUE TITLE
Passer à ignf/validator v4.4.5 pour modèle PPR

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/validator-api#62]
- [x] Ajouter le modèle Plan Prévention des Risques (voir PRs https://github.com/IGNF/validator-api-client/pull/22 et #67 )
- [x] Passer à ignf/validator v4.4.5
- [x] Au passage, compléter la documentation développeur avec les instructions en cas de mise à jour de [ignf/validator](https://github.com/IGNF/validator)

**Comment by cboucheIGN** [comment]
TODO ajouter le modèle Plan Prévention des Riques (PPR).
Le travail est en attente de merge côté validator-api-client
